/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Usuario
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    
    GestorZonas gestor;

// Método del UML
void abrirVentanaZona(String nombreZona) {
    VentanaTrabajadores vt = new VentanaTrabajadores(gestor, nombreZona);
    vt.setVisible(true);
}
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName());

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal(GestorZonas gestor) {
    initComponents();
    this.gestor = gestor;
    setLocationRelativeTo(null);
}
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRecepcion = new javax.swing.JButton();
        btnClasificacion = new javax.swing.JButton();
        btnDespiece = new javax.swing.JButton();
        btnCoccion = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnRecepcion.setText("Recepcion");
        btnRecepcion.addActionListener(this::btnRecepcionActionPerformed);

        btnClasificacion.setText("Clasificacion");
        btnClasificacion.addActionListener(this::btnClasificacionActionPerformed);

        btnDespiece.setText("Despiece");
        btnDespiece.addActionListener(this::btnDespieceActionPerformed);

        btnCoccion.setText("Coccion");
        btnCoccion.addActionListener(this::btnCoccionActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnRecepcion, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(156, 156, 156)
                        .addComponent(btnClasificacion)
                        .addGap(87, 87, 87)
                        .addComponent(btnDespiece)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addComponent(btnCoccion, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(93, 93, 93))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(82, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRecepcion, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClasificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDespiece, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCoccion, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(98, 98, 98))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRecepcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecepcionActionPerformed
abrirVentanaZona("Recepción");        // TODO add your handling code here:
    }//GEN-LAST:event_btnRecepcionActionPerformed

    private void btnClasificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClasificacionActionPerformed
abrirVentanaZona("Clasificación y almacenaje");        // TODO add your handling code here:
    }//GEN-LAST:event_btnClasificacionActionPerformed

    private void btnDespieceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDespieceActionPerformed
abrirVentanaZona("Despiece y eviscere");        // TODO add your handling code here:
    }//GEN-LAST:event_btnDespieceActionPerformed

    private void btnCoccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCoccionActionPerformed
abrirVentanaZona("Cocción al vapor");        // TODO add your handling code here:
    }//GEN-LAST:event_btnCoccionActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClasificacion;
    private javax.swing.JButton btnCoccion;
    private javax.swing.JButton btnDespiece;
    private javax.swing.JButton btnRecepcion;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
