/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Usuario
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    
    GestorZonas gestor;

// Método del UML
void abrirVentanaZona(String nombreZona) {
    VentanaTrabajadores vt = new VentanaTrabajadores(gestor, nombreZona);
    vt.setVisible(true);
}
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName());

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal(GestorZonas gestor) {
    initComponents();
    this.gestor = gestor;
    setLocationRelativeTo(null);
}
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRecepcion = new javax.swing.JButton();
        btnClasificacion = new javax.swing.JButton();
        btnDespiece = new javax.swing.JButton();
        btnCoccion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnRecepcion.setText("btnRecepcion");
        btnRecepcion.addActionListener(this::btnRecepcionActionPerformed);

        btnClasificacion.setText("btnClasificacion");
        btnClasificacion.addActionListener(this::btnClasificacionActionPerformed);

        btnDespiece.setText("btnDespiece");
        btnDespiece.addActionListener(this::btnDespieceActionPerformed);

        btnCoccion.setText("btnCoccion");
        btnCoccion.addActionListener(this::btnCoccionActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(btnRecepcion)
                .addGap(28, 28, 28)
                .addComponent(btnClasificacion)
                .addGap(34, 34, 34)
                .addComponent(btnDespiece)
                .addGap(18, 18, 18)
                .addComponent(btnCoccion)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(162, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRecepcion)
                    .addComponent(btnClasificacion)
                    .addComponent(btnDespiece)
                    .addComponent(btnCoccion))
                .addGap(115, 115, 115))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRecepcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecepcionActionPerformed
abrirVentanaZona("Recepción");        // TODO add your handling code here:
    }//GEN-LAST:event_btnRecepcionActionPerformed

    private void btnClasificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClasificacionActionPerformed
abrirVentanaZona("Clasificación y almacenaje");        // TODO add your handling code here:
    }//GEN-LAST:event_btnClasificacionActionPerformed

    private void btnDespieceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDespieceActionPerformed
abrirVentanaZona("Despiece y eviscere");        // TODO add your handling code here:
    }//GEN-LAST:event_btnDespieceActionPerformed

    private void btnCoccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCoccionActionPerformed
abrirVentanaZona("Cocción al vapor");        // TODO add your handling code here:
    }//GEN-LAST:event_btnCoccionActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClasificacion;
    private javax.swing.JButton btnCoccion;
    private javax.swing.JButton btnDespiece;
    private javax.swing.JButton btnRecepcion;
    // End of variables declaration//GEN-END:variables
}
